-- Generated by scripts/scrape.py. DuckDB views over scraped parquet.
CREATE OR REPLACE VIEW v_buildings AS
SELECT * FROM read_json_auto('data/raw/buildings_from_api.json');

CREATE OR REPLACE VIEW v_readings AS
SELECT * FROM read_parquet('data/raw/readings/**/readings.parquet', hive_partitioning=1);

CREATE OR REPLACE VIEW v_weather AS
SELECT * FROM read_parquet('data/raw/weather.parquet');

CREATE OR REPLACE VIEW v_readings_with_meta AS
SELECT r.*, b.buildingname, b.campus, b.gross_area, b.latitude, b.longitude,
       b.construction_date, b.building_type
FROM v_readings r
LEFT JOIN v_buildings b ON r.siteid = b.buildingnumber;

CREATE OR REPLACE VIEW v_readings_full AS
SELECT rm.*, w.temperature_2m, w.relative_humidity_2m, w.dew_point_2m,
       w.shortwave_radiation, w.wind_speed_10m, w.cloud_cover,
       w.apparent_temperature, w.precipitation
FROM v_readings_with_meta rm
LEFT JOIN v_weather w
  ON date_trunc('hour', rm.reading_time) = w.reading_time;
